config/routes.rb
Rails.application.routes.draw do
  get 'index/index'

  resources :libros
  resources :autors

end

app/models/autor.rb
class Autor < ActiveRecord::Base

 has_many :libros

end

app/models/libro.rb
class Libro < ActiveRecord::Base
  belongs_to :autor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/autors_controller.rb
class AutorsController < ApplicationController
  before_action :set_autor, only: [:show, :edit, :update, :destroy]

  # GET /autors
  # GET /autors.json
  def index
    @autors = Autor.all
  end

  # GET /autors/1
  # GET /autors/1.json
  def show
  end

  # GET /autors/new
  def new
    @autor = Autor.new
  end

  # GET /autors/1/edit
  def edit
  end

  # POST /autors
  # POST /autors.json
  def create
    @autor = Autor.new(autor_params)

    respond_to do |format|
      if @autor.save
        format.html { redirect_to @autor, notice: 'Autor was successfully created.' }
        format.json { render :show, status: :created, location: @autor }
      else
        format.html { render :new }
        format.json { render json: @autor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /autors/1
  # PATCH/PUT /autors/1.json
  def update
    respond_to do |format|
      if @autor.update(autor_params)
        format.html { redirect_to @autor, notice: 'Autor was successfully updated.' }
        format.json { render :show, status: :ok, location: @autor }
      else
        format.html { render :edit }
        format.json { render json: @autor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autors/1
  # DELETE /autors/1.json
  def destroy
    @autor.destroy
    respond_to do |format|
      format.html { redirect_to autors_url, notice: 'Autor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_autor
      @autor = Autor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def autor_params
      params.require(:autor).permit(:name)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  before_action :set_libro, only: [:show, :edit, :update, :destroy]

  # GET /libros
  # GET /libros.json
  def index
    @libros = Libro.all
    @autors = Autor.all
  end

  # GET /libros/1
  # GET /libros/1.json
  def show
  end

  # GET /libros/new
  def new
    @libro = Libro.new
     @autors = Autor.all
  end

  # GET /libros/1/edit
  def edit
     @autors = Autor.all
  end

  # POST /libros
  # POST /libros.json
  def create
    @libro = Libro.new(libro_params)

    respond_to do |format|
      if @libro.save
        format.html { redirect_to @libro, notice: 'Libro was successfully created.' }
        format.json { render :show, status: :created, location: @libro }
      else
        format.html { render :new }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libros/1
  # PATCH/PUT /libros/1.json
  def update
    respond_to do |format|
      if @libro.update(libro_params)
        format.html { redirect_to @libro, notice: 'Libro was successfully updated.' }
        format.json { render :show, status: :ok, location: @libro }
      else
        format.html { render :edit }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @libro.destroy
    respond_to do |format|
      format.html { redirect_to libros_url, notice: 'Libro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro
      @libro = Libro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def libro_params
      params.require(:libro).permit(:name, :autor_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autors_helper.rb
module AutorsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/autors/_form.html.erb
<%= form_for(@autor) do |f| %>
  <% if @autor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@autor.errors.count, "error") %> Error, no se puede guardar este autor:</h2>

      <ul>
      <% @autor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Nombre:" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/autors/edit.html.erb
<h3>Editar Autor</h3>

<%= render 'form' %>

<%= link_to 'Visualizar', @autor %> |
<%= link_to 'Atrás', autors_path %>

app/views/autors/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Lista Autores</h3>


<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @autors.each do |autor| %>
      <tr>
        <td><%= autor.name %></td>
        <td><%= link_to 'Visualizar', autor %></td>
        <td><%= link_to 'Editar', edit_autor_path(autor) %></td>
        <td><%= link_to 'Eliminar', autor, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Autor', new_autor_path %>

app/views/autors/new.html.erb
<h3>Nuevo Autor</h3>

<%= render 'form' %>

<%= link_to 'Atrás', autors_path %>

app/views/autors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @autor.name %>
</p>

<%= link_to 'Editar', edit_autor_path(@autor) %> |
<%= link_to 'Atrás', autors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LibrosRuby</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <h1>Gestor de Libros</h1>
<ul>

	<li><a href="..\autors">Autores</a></li>
	<li><a href="..\libros">Libros</a></li>
</ul>
</head>

<body>

<%= yield %>

</body>

</html>

app/views/libros/_form.html.erb
<%= form_for(@libro) do |f| %>
  <% if @libro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@libro.errors.count, "error") %> Error, no se puede guardar este libro:</h2>

      <ul>
      <% @libro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Nombre:" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :autor_id %><br>
    <%= f.select(:autor_id) do %>
      <%@autors.each do |a| %>
        <%= content_tag(:option, a.name, value:a.id)%>
      <%end%>
    <%end%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/libros/edit.html.erb
<h3>Editar Libro</h3>

<%= render 'form' %>

<%= link_to 'Visualizar', @libro %> |
<%= link_to 'Atrás', libros_path %>

app/views/libros/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Lista Libros</h3>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Autor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libros.each do |libro| %>
      <tr>
        <td><%= libro.name %></td>
        <td><%= libro.autor.name %></td>
        <td><%= link_to 'Visualizar', libro %></td>
        <td><%= link_to 'Editar', edit_libro_path(libro) %></td>
        <td><%= link_to 'Eliminar', libro, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Libro', new_libro_path %>

app/views/libros/new.html.erb
<h3>Nuevo Libro</h3>

<%= render 'form' %>

<%= link_to 'Atrás', libros_path %>

app/views/libros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @libro.name %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @libro.autor.name %>
</p>

<%= link_to 'Editar', edit_libro_path(@libro) %> |
<%= link_to 'Atrás', libros_path %>